# Generated by Django 3.2.3 on 2021-05-19 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='next_node',
        ),
        migrations.AddField(
            model_name='content',
            name='prev_node',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_node', to='content.content'),
        ),
    ]
