# Generated by Django 3.2.3 on 2021-05-23 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210519_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='prev_node',
        ),
    ]
