# Generated by Django 3.2.3 on 2021-05-23 09:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_content_prev_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='children',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(primary_key=True), default=[], size=None),
            preserve_default=False,
        ),
    ]
